main_ottimizzato.exe < ../tests/archivio_test_aperti/open_1.txt > ../tests/archivio_test_aperti/esiti/open_1.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_2.txt > ../tests/archivio_test_aperti/esiti/open_2.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_3.txt > ../tests/archivio_test_aperti/esiti/open_3.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_4.txt > ../tests/archivio_test_aperti/esiti/open_4.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_5.txt > ../tests/archivio_test_aperti/esiti/open_5.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_6.txt > ../tests/archivio_test_aperti/esiti/open_6.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_7.txt > ../tests/archivio_test_aperti/esiti/open_7.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_8.txt > ../tests/archivio_test_aperti/esiti/open_8.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_9.txt > ../tests/archivio_test_aperti/esiti/open_9.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_10.txt > ../tests/archivio_test_aperti/esiti/open_10.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_11.txt > ../tests/archivio_test_aperti/esiti/open_11.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_12.txt > ../tests/archivio_test_aperti/esiti/open_12.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_13.txt > ../tests/archivio_test_aperti/esiti/open_13.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_14.txt > ../tests/archivio_test_aperti/esiti/open_14.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_15.txt > ../tests/archivio_test_aperti/esiti/open_15.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_16.txt > ../tests/archivio_test_aperti/esiti/open_16.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_17.txt > ../tests/archivio_test_aperti/esiti/open_17.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_18.txt > ../tests/archivio_test_aperti/esiti/open_18.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_19.txt > ../tests/archivio_test_aperti/esiti/open_19.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_20.txt > ../tests/archivio_test_aperti/esiti/open_20.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_21.txt > ../tests/archivio_test_aperti/esiti/open_21.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_22.txt > ../tests/archivio_test_aperti/esiti/open_22.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_23.txt > ../tests/archivio_test_aperti/esiti/open_23.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_24.txt > ../tests/archivio_test_aperti/esiti/open_24.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_25.txt > ../tests/archivio_test_aperti/esiti/open_25.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_26.txt > ../tests/archivio_test_aperti/esiti/open_26.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_27.txt > ../tests/archivio_test_aperti/esiti/open_27.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_28.txt > ../tests/archivio_test_aperti/esiti/open_28.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_29.txt > ../tests/archivio_test_aperti/esiti/open_29.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_30.txt > ../tests/archivio_test_aperti/esiti/open_30.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_31.txt > ../tests/archivio_test_aperti/esiti/open_31.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_32.txt > ../tests/archivio_test_aperti/esiti/open_32.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_33.txt > ../tests/archivio_test_aperti/esiti/open_33.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_34.txt > ../tests/archivio_test_aperti/esiti/open_34.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_35.txt > ../tests/archivio_test_aperti/esiti/open_35.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_36.txt > ../tests/archivio_test_aperti/esiti/open_36.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_37.txt > ../tests/archivio_test_aperti/esiti/open_37.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_38.txt > ../tests/archivio_test_aperti/esiti/open_38.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_39.txt > ../tests/archivio_test_aperti/esiti/open_39.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_40.txt > ../tests/archivio_test_aperti/esiti/open_40.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_41.txt > ../tests/archivio_test_aperti/esiti/open_41.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_42.txt > ../tests/archivio_test_aperti/esiti/open_42.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_43.txt > ../tests/archivio_test_aperti/esiti/open_43.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_44.txt > ../tests/archivio_test_aperti/esiti/open_44.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_45.txt > ../tests/archivio_test_aperti/esiti/open_45.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_46.txt > ../tests/archivio_test_aperti/esiti/open_46.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_47.txt > ../tests/archivio_test_aperti/esiti/open_47.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_48.txt > ../tests/archivio_test_aperti/esiti/open_48.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_49.txt > ../tests/archivio_test_aperti/esiti/open_49.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_50.txt > ../tests/archivio_test_aperti/esiti/open_50.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_51.txt > ../tests/archivio_test_aperti/esiti/open_51.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_52.txt > ../tests/archivio_test_aperti/esiti/open_52.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_53.txt > ../tests/archivio_test_aperti/esiti/open_53.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_54.txt > ../tests/archivio_test_aperti/esiti/open_54.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_55.txt > ../tests/archivio_test_aperti/esiti/open_55.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_56.txt > ../tests/archivio_test_aperti/esiti/open_56.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_57.txt > ../tests/archivio_test_aperti/esiti/open_57.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_58.txt > ../tests/archivio_test_aperti/esiti/open_58.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_59.txt > ../tests/archivio_test_aperti/esiti/open_59.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_60.txt > ../tests/archivio_test_aperti/esiti/open_60.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_61.txt > ../tests/archivio_test_aperti/esiti/open_61.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_62.txt > ../tests/archivio_test_aperti/esiti/open_62.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_63.txt > ../tests/archivio_test_aperti/esiti/open_63.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_64.txt > ../tests/archivio_test_aperti/esiti/open_64.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_65.txt > ../tests/archivio_test_aperti/esiti/open_65.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_66.txt > ../tests/archivio_test_aperti/esiti/open_66.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_67.txt > ../tests/archivio_test_aperti/esiti/open_67.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_68.txt > ../tests/archivio_test_aperti/esiti/open_68.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_69.txt > ../tests/archivio_test_aperti/esiti/open_69.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_70.txt > ../tests/archivio_test_aperti/esiti/open_70.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_71.txt > ../tests/archivio_test_aperti/esiti/open_71.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_72.txt > ../tests/archivio_test_aperti/esiti/open_72.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_73.txt > ../tests/archivio_test_aperti/esiti/open_73.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_74.txt > ../tests/archivio_test_aperti/esiti/open_74.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_75.txt > ../tests/archivio_test_aperti/esiti/open_75.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_76.txt > ../tests/archivio_test_aperti/esiti/open_76.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_77.txt > ../tests/archivio_test_aperti/esiti/open_77.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_78.txt > ../tests/archivio_test_aperti/esiti/open_78.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_79.txt > ../tests/archivio_test_aperti/esiti/open_79.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_80.txt > ../tests/archivio_test_aperti/esiti/open_80.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_81.txt > ../tests/archivio_test_aperti/esiti/open_81.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_82.txt > ../tests/archivio_test_aperti/esiti/open_82.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_83.txt > ../tests/archivio_test_aperti/esiti/open_83.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_84.txt > ../tests/archivio_test_aperti/esiti/open_84.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_85.txt > ../tests/archivio_test_aperti/esiti/open_85.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_86.txt > ../tests/archivio_test_aperti/esiti/open_86.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_87.txt > ../tests/archivio_test_aperti/esiti/open_87.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_88.txt > ../tests/archivio_test_aperti/esiti/open_88.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_89.txt > ../tests/archivio_test_aperti/esiti/open_89.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_90.txt > ../tests/archivio_test_aperti/esiti/open_90.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_91.txt > ../tests/archivio_test_aperti/esiti/open_91.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_92.txt > ../tests/archivio_test_aperti/esiti/open_92.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_93.txt > ../tests/archivio_test_aperti/esiti/open_93.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_94.txt > ../tests/archivio_test_aperti/esiti/open_94.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_95.txt > ../tests/archivio_test_aperti/esiti/open_95.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_96.txt > ../tests/archivio_test_aperti/esiti/open_96.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_97.txt > ../tests/archivio_test_aperti/esiti/open_97.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_98.txt > ../tests/archivio_test_aperti/esiti/open_98.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_99.txt > ../tests/archivio_test_aperti/esiti/open_99.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_100.txt > ../tests/archivio_test_aperti/esiti/open_100.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_101.txt > ../tests/archivio_test_aperti/esiti/open_101.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_102.txt > ../tests/archivio_test_aperti/esiti/open_102.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_103.txt > ../tests/archivio_test_aperti/esiti/open_103.output.txt
main_ottimizzato.exe < ../tests/archivio_test_aperti/open_104.txt > ../tests/archivio_test_aperti/esiti/open_104.output.txt
